const TYPE_IDS = `acai_shop afghani_restaurant african_restaurant american_restaurant argentinian_restaurant asian_fusion_restaurant asian_restaurant australian_restaurant austrian_restaurant bagel_shop bakery bangladeshi_restaurant bar bar_and_grill barbecue_restaurant basque_restaurant bavarian_restaurant beer_garden belgian_restaurant bistro brazilian_restaurant breakfast_restaurant brewery brewpub british_restaurant brunch_restaurant buffet_restaurant burmese_restaurant burrito_restaurant cafe cafeteria cajun_restaurant cake_shop californian_restaurant cambodian_restaurant candy_store cantonese_restaurant caribbean_restaurant cat_cafe chicken_restaurant chicken_wings_restaurant chilean_restaurant chinese_noodle_restaurant chinese_restaurant chocolate_factory chocolate_shop cocktail_bar coffee_roastery coffee_shop coffee_stand colombian_restaurant confectionery croatian_restaurant cuban_restaurant czech_restaurant danish_restaurant deli dessert_restaurant dessert_shop dim_sum_restaurant diner dog_cafe donut_shop dumpling_restaurant dutch_restaurant eastern_european_restaurant ethiopian_restaurant european_restaurant falafel_restaurant family_restaurant fast_food_restaurant filipino_restaurant fine_dining_restaurant fish_and_chips_restaurant fondue_restaurant food_court french_restaurant fusion_restaurant gastropub german_restaurant greek_restaurant gyro_restaurant halal_restaurant hamburger_restaurant hawaiian_restaurant hookah_bar hot_dog_restaurant hot_dog_stand hot_pot_restaurant hungarian_restaurant ice_cream_shop indian_restaurant indonesian_restaurant irish_pub irish_restaurant israeli_restaurant italian_restaurant japanese_curry_restaurant japanese_izakaya_restaurant japanese_restaurant juice_shop kebab_shop korean_barbecue_restaurant korean_restaurant latin_american_restaurant lebanese_restaurant lounge_bar malaysian_restaurant meal_delivery meal_takeaway mediterranean_restaurant mexican_restaurant middle_eastern_restaurant mongolian_barbecue_restaurant moroccan_restaurant noodle_shop north_indian_restaurant oyster_bar_restaurant pakistani_restaurant pastry_shop persian_restaurant peruvian_restaurant pizza_delivery pizza_restaurant polish_restaurant portuguese_restaurant pub ramen_restaurant restaurant romanian_restaurant russian_restaurant salad_shop sandwich_shop scandinavian_restaurant seafood_restaurant shawarma_restaurant snack_bar soul_food_restaurant soup_restaurant south_american_restaurant south_indian_restaurant southwestern_us_restaurant spanish_restaurant sports_bar sri_lankan_restaurant steak_house sushi_restaurant swiss_restaurant taco_restaurant taiwanese_restaurant tapas_restaurant tea_house tex_mex_restaurant thai_restaurant tibetan_restaurant tonkatsu_restaurant turkish_restaurant ukrainian_restaurant vegan_restaurant vegetarian_restaurant vietnamese_restaurant western_restaurant wine_bar winery yakiniku_restaurant yakitori_restaurant`.split(" ");

const ZH = Object.freeze({ restaurant: "一般餐廳", cafe: "咖啡廳", coffee_shop: "咖啡店", bakery: "烘焙店", bar: "酒吧", breakfast_restaurant: "早餐店", brunch_restaurant: "早午餐", buffet_restaurant: "自助餐", chinese_restaurant: "中式餐廳", cantonese_restaurant: "粵菜", dim_sum_restaurant: "港式點心", taiwanese_restaurant: "台灣料理", japanese_restaurant: "日本料理", japanese_izakaya_restaurant: "居酒屋", korean_restaurant: "韓式料理", korean_barbecue_restaurant: "韓式燒肉", thai_restaurant: "泰式料理", vietnamese_restaurant: "越南料理", italian_restaurant: "義式料理", french_restaurant: "法式料理", american_restaurant: "美式料理", mexican_restaurant: "墨西哥料理", indian_restaurant: "印度料理", hot_pot_restaurant: "火鍋", barbecue_restaurant: "燒烤", yakiniku_restaurant: "日式燒肉", steak_house: "牛排館", seafood_restaurant: "海鮮餐廳", sushi_restaurant: "壽司", ramen_restaurant: "拉麵", noodle_shop: "麵店", chinese_noodle_restaurant: "中式麵店", dumpling_restaurant: "餃子店", vegetarian_restaurant: "素食", vegan_restaurant: "純素", dessert_shop: "甜點店", dessert_restaurant: "甜點餐廳", ice_cream_shop: "冰淇淋店", tea_house: "茶館", juice_shop: "果汁店", fast_food_restaurant: "速食", meal_takeaway: "外帶餐點", meal_delivery: "餐點外送", food_court: "美食街", pizza_restaurant: "披薩", hamburger_restaurant: "漢堡", sandwich_shop: "三明治", soup_restaurant: "湯品", fine_dining_restaurant: "精緻餐飲" });

function englishLabel(id) {
  return id.split("_").map((word) => word[0].toUpperCase() + word.slice(1)).join(" ");
}

export const FOOD_TYPES = Object.freeze(TYPE_IDS.map((id) => ({
  id,
  label: ZH[id] || englishLabel(id),
  group: id.endsWith("_restaurant") || id === "restaurant" || id === "steak_house" ? "料理與餐廳" : "飲品、甜點與其他"
})));

export const POPULAR_FOOD_TYPES = Object.freeze(["restaurant", "cafe", "coffee_shop", "bakery", "breakfast_restaurant", "brunch_restaurant", "chinese_restaurant", "taiwanese_restaurant", "japanese_restaurant", "korean_restaurant", "hot_pot_restaurant", "barbecue_restaurant", "seafood_restaurant", "vegetarian_restaurant"]);
